name: notebook
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - jupyterlab >=3.0
  - jupyter-server-proxy
  - scikit-learn
  - pandas
  - beautifulsoup4
  - skyfield
  - matplotlib
  - r-base ==4.0
  - r-tidyverse
  - r-httpuv
  - r-callr
  - r-jsonlite
  - r-reticulate
  - r-qrcode
  # - requests
  # - tornado
  - pip:
    - pyqrcode
    - usd-core
    - -e ../plotAR-py
