name: notebook
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - jupyterlab >=3.0
  - jupyter-server-proxy
  - scikit-learn
  # - pandas
  # - numpy
  # - requests
  # - tornado
  - pip:
    - pyqrcode
    - usd-core
    - -e ../plotVR-py
